/*
 * generated by Xtext 2.10.0
 */
package se.mdh.idt.xmarte

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XMarteRuntimeModule extends AbstractXMarteRuntimeModule {
}
