/*
 * generated by Xtext 2.10.0
 */
package se.mdh.idt.xmarte

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XMarteStandaloneSetup extends XMarteStandaloneSetupGenerated {

	def static void doSetup() {
		new XMarteStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
